import { MigrationInterface, QueryRunner } from 'typeorm';
export class InitialVesperDemo1789731000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE TYPE \"public\".\"avatar_orientation_enum\" AS ENUM('square', 'portrait', 'landscape')");
    await queryRunner.query("CREATE TABLE \"avatar\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"ownerId\" character varying NOT NULL, \"source\" character varying NOT NULL, \"orientation\" \"public\".\"avatar_orientation_enum\" NOT NULL, \"dominant\" character varying NOT NULL, \"height\" character varying NOT NULL, \"width\" character varying NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_50e36da9d45349941038eaf149d\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"favorite\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"ownerId\" uuid NOT NULL, \"artworkId\" uuid NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_495675cec4fb09666704e4f610f\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TYPE \"public\".\"cover_orientation_enum\" AS ENUM('square', 'portrait', 'landscape')");
    await queryRunner.query("CREATE TABLE \"cover\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"source\" character varying NOT NULL, \"orientation\" \"public\".\"cover_orientation_enum\" NOT NULL, \"dominant\" character varying NOT NULL, \"height\" character varying NOT NULL, \"width\" character varying NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_09847db42fd93d7e6b49f318629\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TYPE \"public\".\"media_orientation_enum\" AS ENUM('square', 'portrait', 'landscape')");
    await queryRunner.query("CREATE TABLE \"media\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"source\" character varying NOT NULL, \"orientation\" \"public\".\"media_orientation_enum\" NOT NULL, \"dominant\" character varying NOT NULL, \"height\" character varying NOT NULL, \"width\" character varying NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_f4e0fcac36e050de337b670d8bd\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"discount\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"name\" character varying NOT NULL, \"discount\" integer NOT NULL, \"active\" boolean NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_d05d8712e429673e459e7f1cddb\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TYPE \"public\".\"license_type_enum\" AS ENUM('personal', 'commercial')");
    await queryRunner.query("CREATE TYPE \"public\".\"license_usage_enum\" AS ENUM('individual', 'business')");
    await queryRunner.query("CREATE TABLE \"license\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"ownerId\" uuid NOT NULL, \"sellerId\" uuid NOT NULL, \"artworkId\" uuid NOT NULL, \"fingerprint\" character varying NOT NULL, \"assignee\" character varying NOT NULL, \"assigneeIdentifier\" character varying NOT NULL, \"assignor\" character varying NOT NULL, \"assignorIdentifier\" character varying NOT NULL, \"company\" character varying NOT NULL, \"type\" \"public\".\"license_type_enum\" NOT NULL, \"usage\" \"public\".\"license_usage_enum\", \"active\" boolean NOT NULL, \"price\" integer NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_f168ac1ca5ba87286d03b2ef905\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"review\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"orderId\" character varying NOT NULL, \"artworkId\" uuid NOT NULL, \"reviewerId\" uuid NOT NULL, \"revieweeId\" uuid NOT NULL, \"rating\" integer NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_2e4299a343a81574217255c00ca\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TYPE \"public\".\"order_type_enum\" AS ENUM('free', 'commercial')");
    await queryRunner.query("CREATE TYPE \"public\".\"order_status_enum\" AS ENUM('completed', 'canceled', 'processing')");
    await queryRunner.query("CREATE TABLE \"order\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"buyerId\" uuid NOT NULL, \"sellerId\" uuid NOT NULL, \"artworkId\" uuid NOT NULL, \"versionId\" uuid NOT NULL, \"licenseId\" uuid NOT NULL, \"discountId\" uuid, \"reviewId\" uuid, \"intentId\" character varying, \"spent\" integer NOT NULL, \"earned\" integer NOT NULL, \"fee\" integer NOT NULL, \"type\" \"public\".\"order_type_enum\" NOT NULL, \"status\" \"public\".\"order_status_enum\" NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"REL_31e820731c1a6c3e6d4a3aeb82\" UNIQUE (\"licenseId\"), CONSTRAINT \"REL_1828ae59cb61e9e6edf91c266b\" UNIQUE (\"reviewId\"), CONSTRAINT \"PK_1031171c13130102495201e3e20\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"tag\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"title\" character varying NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_8e4052373c579afc1471f526760\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TYPE \"public\".\"version_availability_enum\" AS ENUM('available', 'unavailable')");
    await queryRunner.query("CREATE TYPE \"public\".\"version_type_enum\" AS ENUM('free', 'commercial', 'unavailable')");
    await queryRunner.query("CREATE TYPE \"public\".\"version_license_enum\" AS ENUM('personal', 'commercial', 'unavailable')");
    await queryRunner.query("CREATE TYPE \"public\".\"version_use_enum\" AS ENUM('separate', 'included', 'unavailable')");
    await queryRunner.query("CREATE TABLE \"version\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"artworkId\" character varying NOT NULL, \"title\" character varying NOT NULL, \"category\" character varying, \"description\" character varying NOT NULL, \"availability\" \"public\".\"version_availability_enum\" NOT NULL, \"type\" \"public\".\"version_type_enum\" NOT NULL, \"license\" \"public\".\"version_license_enum\" NOT NULL, \"use\" \"public\".\"version_use_enum\" NOT NULL, \"personal\" integer NOT NULL, \"commercial\" integer NOT NULL, \"coverId\" uuid NOT NULL, \"mediaId\" uuid NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"generated\" boolean NOT NULL DEFAULT false, CONSTRAINT \"PK_4fb5fbb15a43da9f35493107b1d\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"intent\" (\"id\" character varying NOT NULL, \"serial\" SERIAL NOT NULL, \"ownerId\" uuid NOT NULL, \"versionId\" uuid NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_513a9beef6edc5701fbd955321d\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TYPE \"public\".\"notification_type_enum\" AS ENUM('order', 'review', 'comment')");
    await queryRunner.query("CREATE TABLE \"notification\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"receiverId\" uuid NOT NULL, \"link\" character varying NOT NULL, \"ref\" character varying NOT NULL, \"type\" \"public\".\"notification_type_enum\" NOT NULL, \"read\" boolean NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_705b6c7cdf9b2c2ff7ac7872cb7\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"view\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"ip\" character varying NOT NULL, \"ownerId\" uuid, \"artworkId\" uuid NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_86cfb9e426c77d60b900fe2b543\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"user\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"email\" character varying, \"name\" character varying, \"fullName\" character varying NOT NULL, \"password\" character varying NOT NULL, \"avatarId\" uuid, \"description\" character varying NOT NULL DEFAULT '', \"country\" character varying NOT NULL DEFAULT '', \"customWork\" boolean NOT NULL DEFAULT false, \"displayFavorites\" boolean NOT NULL DEFAULT true, \"resetToken\" character varying NOT NULL DEFAULT '', \"resetExpiry\" TIMESTAMP WITH TIME ZONE DEFAULT now(), \"jwtVersion\" integer NOT NULL DEFAULT '0', \"stripeId\" character varying NOT NULL DEFAULT '', \"onboarded\" boolean NOT NULL DEFAULT false, \"verificationToken\" character varying NOT NULL DEFAULT '', \"verificationExpiry\" TIMESTAMP WITH TIME ZONE DEFAULT now(), \"verified\" boolean NOT NULL DEFAULT false, \"active\" boolean NOT NULL DEFAULT true, \"demoExpiresAt\" TIMESTAMP WITH TIME ZONE, \"demoWrites\" integer NOT NULL DEFAULT '0', \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE DEFAULT now(), CONSTRAINT \"UQ_e12875dfb3b1d92d7d7c5377e22\" UNIQUE (\"email\"), CONSTRAINT \"UQ_065d4d8f3b5adb4a08841eae3c8\" UNIQUE (\"name\"), CONSTRAINT \"REL_58f5c71eaab331645112cf8cfa\" UNIQUE (\"avatarId\"), CONSTRAINT \"PK_cace4a159ff9f2512dd42373760\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"like\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"ownerId\" uuid NOT NULL, \"commentId\" uuid NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_eff3e46d24d416b52a7e0ae4159\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"comment\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"ownerId\" uuid NOT NULL, \"artworkId\" uuid NOT NULL, \"content\" character varying NOT NULL, \"modified\" boolean NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_0b0e4bbc8415ec426f87f3a88e2\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TYPE \"public\".\"artwork_visibility_enum\" AS ENUM('visible', 'invisible')");
    await queryRunner.query("CREATE TABLE \"artwork\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"ownerId\" uuid NOT NULL, \"currentId\" uuid, \"active\" boolean NOT NULL, \"visibility\" \"public\".\"artwork_visibility_enum\" NOT NULL, \"generated\" boolean NOT NULL DEFAULT false, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"REL_230d2b81ff20a84ac87a6b09f2\" UNIQUE (\"currentId\"), CONSTRAINT \"PK_ee2e7c5ad7226179d4113a96fa8\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"demo_upload\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"ownerId\" uuid NOT NULL, \"mimeType\" character varying NOT NULL, \"content\" bytea NOT NULL, \"bytes\" integer NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_321182bc0250cbde4d9c1e670ad\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TYPE \"public\".\"ticket_status_enum\" AS ENUM('pending', 'resolved', 'closed')");
    await queryRunner.query("CREATE TABLE \"ticket\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"serial\" SERIAL NOT NULL, \"ownerId\" uuid NOT NULL, \"title\" character varying NOT NULL, \"body\" character varying NOT NULL, \"attachment\" character varying NOT NULL, \"status\" \"public\".\"ticket_status_enum\" NOT NULL, \"created\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), \"updated\" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT \"PK_d9a0835407701eb86f874474b7c\" PRIMARY KEY (\"id\"))");
    await queryRunner.query("CREATE TABLE \"version_tags_tag\" (\"versionId\" uuid NOT NULL, \"tagId\" uuid NOT NULL, CONSTRAINT \"PK_27d74871ded46c266c88f132272\" PRIMARY KEY (\"versionId\", \"tagId\"))");
    await queryRunner.query("CREATE INDEX \"IDX_e21fe37e3bf2e746857a838293\" ON \"version_tags_tag\"  (\"versionId\") ");
    await queryRunner.query("CREATE INDEX \"IDX_0c1467bd2ae2fa944b3dcdf8b9\" ON \"version_tags_tag\"  (\"tagId\") ");
    await queryRunner.query("ALTER TABLE \"favorite\" ADD CONSTRAINT \"FK_c58c744f101a916108d5ee7a7a3\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"favorite\" ADD CONSTRAINT \"FK_268e16a2e8408d2e70bf77b8ae2\" FOREIGN KEY (\"artworkId\") REFERENCES \"artwork\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"license\" ADD CONSTRAINT \"FK_78fd970f6ec6ef41f8eae138e58\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"license\" ADD CONSTRAINT \"FK_e368cd7219d66f7e97dd52ce91a\" FOREIGN KEY (\"sellerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"license\" ADD CONSTRAINT \"FK_05d20a9b7c596fe15467a4d1279\" FOREIGN KEY (\"artworkId\") REFERENCES \"artwork\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"review\" ADD CONSTRAINT \"FK_630f200bca6cd83918a0a4479ff\" FOREIGN KEY (\"artworkId\") REFERENCES \"artwork\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"review\" ADD CONSTRAINT \"FK_34413365b39e3bf5bea866569b4\" FOREIGN KEY (\"reviewerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"review\" ADD CONSTRAINT \"FK_2bbe7b10857bd93ca651699037b\" FOREIGN KEY (\"revieweeId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"order\" ADD CONSTRAINT \"FK_20981b2b68bf03393c44dd1b9d7\" FOREIGN KEY (\"buyerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"order\" ADD CONSTRAINT \"FK_8a583acc24e13bcf84b1b9d0d20\" FOREIGN KEY (\"sellerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"order\" ADD CONSTRAINT \"FK_530376662de2b4138653194be2b\" FOREIGN KEY (\"artworkId\") REFERENCES \"artwork\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"order\" ADD CONSTRAINT \"FK_ddd586ef22affe071c51b2cd5eb\" FOREIGN KEY (\"versionId\") REFERENCES \"version\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"order\" ADD CONSTRAINT \"FK_31e820731c1a6c3e6d4a3aeb82f\" FOREIGN KEY (\"licenseId\") REFERENCES \"license\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"order\" ADD CONSTRAINT \"FK_4c1bbd44f6614bf518204e1d5ca\" FOREIGN KEY (\"discountId\") REFERENCES \"discount\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"order\" ADD CONSTRAINT \"FK_1828ae59cb61e9e6edf91c266bb\" FOREIGN KEY (\"reviewId\") REFERENCES \"review\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"version\" ADD CONSTRAINT \"FK_a699c3dbe56144ca43f3f9bae2b\" FOREIGN KEY (\"coverId\") REFERENCES \"cover\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"version\" ADD CONSTRAINT \"FK_4defcd1ec277c0c05cfc963e607\" FOREIGN KEY (\"mediaId\") REFERENCES \"media\"(\"id\") ON DELETE NO ACTION ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"intent\" ADD CONSTRAINT \"FK_cd0a2fcca5dee860f834b150da8\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"intent\" ADD CONSTRAINT \"FK_26507b5ff9d0e4ad2c04a8ef6a4\" FOREIGN KEY (\"versionId\") REFERENCES \"version\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"notification\" ADD CONSTRAINT \"FK_758d70a0e61243171e785989070\" FOREIGN KEY (\"receiverId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"view\" ADD CONSTRAINT \"FK_fc603fe5334069bf54326670f61\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"view\" ADD CONSTRAINT \"FK_a9548bcd91be058142c878c6656\" FOREIGN KEY (\"artworkId\") REFERENCES \"artwork\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"user\" ADD CONSTRAINT \"FK_58f5c71eaab331645112cf8cfa5\" FOREIGN KEY (\"avatarId\") REFERENCES \"avatar\"(\"id\") ON DELETE SET NULL ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"like\" ADD CONSTRAINT \"FK_5cc8feaa1472fabae24b0bcd58a\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"like\" ADD CONSTRAINT \"FK_d86e0a3eeecc21faa0da415a18a\" FOREIGN KEY (\"commentId\") REFERENCES \"comment\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"comment\" ADD CONSTRAINT \"FK_b8804d1590ac402b52f3e945162\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"comment\" ADD CONSTRAINT \"FK_eff3e064e14bab0bf20647acf35\" FOREIGN KEY (\"artworkId\") REFERENCES \"artwork\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"artwork\" ADD CONSTRAINT \"FK_51a38a5e62b09660e9eda3827bb\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"artwork\" ADD CONSTRAINT \"FK_230d2b81ff20a84ac87a6b09f23\" FOREIGN KEY (\"currentId\") REFERENCES \"version\"(\"id\") ON DELETE SET NULL ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"demo_upload\" ADD CONSTRAINT \"FK_6e3da32969deec562c8777813ce\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"ticket\" ADD CONSTRAINT \"FK_79f2353f877e8bc35dd0101388a\" FOREIGN KEY (\"ownerId\") REFERENCES \"user\"(\"id\") ON DELETE CASCADE ON UPDATE NO ACTION");
    await queryRunner.query("ALTER TABLE \"version_tags_tag\" ADD CONSTRAINT \"FK_e21fe37e3bf2e746857a8382930\" FOREIGN KEY (\"versionId\") REFERENCES \"version\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE");
    await queryRunner.query("ALTER TABLE \"version_tags_tag\" ADD CONSTRAINT \"FK_0c1467bd2ae2fa944b3dcdf8b93\" FOREIGN KEY (\"tagId\") REFERENCES \"tag\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE");
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("ALTER TABLE \"version_tags_tag\" DROP CONSTRAINT \"FK_0c1467bd2ae2fa944b3dcdf8b93\"");
    await queryRunner.query("ALTER TABLE \"version_tags_tag\" DROP CONSTRAINT \"FK_e21fe37e3bf2e746857a8382930\"");
    await queryRunner.query("ALTER TABLE \"ticket\" DROP CONSTRAINT \"FK_79f2353f877e8bc35dd0101388a\"");
    await queryRunner.query("ALTER TABLE \"demo_upload\" DROP CONSTRAINT \"FK_6e3da32969deec562c8777813ce\"");
    await queryRunner.query("ALTER TABLE \"artwork\" DROP CONSTRAINT \"FK_230d2b81ff20a84ac87a6b09f23\"");
    await queryRunner.query("ALTER TABLE \"artwork\" DROP CONSTRAINT \"FK_51a38a5e62b09660e9eda3827bb\"");
    await queryRunner.query("ALTER TABLE \"comment\" DROP CONSTRAINT \"FK_eff3e064e14bab0bf20647acf35\"");
    await queryRunner.query("ALTER TABLE \"comment\" DROP CONSTRAINT \"FK_b8804d1590ac402b52f3e945162\"");
    await queryRunner.query("ALTER TABLE \"like\" DROP CONSTRAINT \"FK_d86e0a3eeecc21faa0da415a18a\"");
    await queryRunner.query("ALTER TABLE \"like\" DROP CONSTRAINT \"FK_5cc8feaa1472fabae24b0bcd58a\"");
    await queryRunner.query("ALTER TABLE \"user\" DROP CONSTRAINT \"FK_58f5c71eaab331645112cf8cfa5\"");
    await queryRunner.query("ALTER TABLE \"view\" DROP CONSTRAINT \"FK_a9548bcd91be058142c878c6656\"");
    await queryRunner.query("ALTER TABLE \"view\" DROP CONSTRAINT \"FK_fc603fe5334069bf54326670f61\"");
    await queryRunner.query("ALTER TABLE \"notification\" DROP CONSTRAINT \"FK_758d70a0e61243171e785989070\"");
    await queryRunner.query("ALTER TABLE \"intent\" DROP CONSTRAINT \"FK_26507b5ff9d0e4ad2c04a8ef6a4\"");
    await queryRunner.query("ALTER TABLE \"intent\" DROP CONSTRAINT \"FK_cd0a2fcca5dee860f834b150da8\"");
    await queryRunner.query("ALTER TABLE \"version\" DROP CONSTRAINT \"FK_4defcd1ec277c0c05cfc963e607\"");
    await queryRunner.query("ALTER TABLE \"version\" DROP CONSTRAINT \"FK_a699c3dbe56144ca43f3f9bae2b\"");
    await queryRunner.query("ALTER TABLE \"order\" DROP CONSTRAINT \"FK_1828ae59cb61e9e6edf91c266bb\"");
    await queryRunner.query("ALTER TABLE \"order\" DROP CONSTRAINT \"FK_4c1bbd44f6614bf518204e1d5ca\"");
    await queryRunner.query("ALTER TABLE \"order\" DROP CONSTRAINT \"FK_31e820731c1a6c3e6d4a3aeb82f\"");
    await queryRunner.query("ALTER TABLE \"order\" DROP CONSTRAINT \"FK_ddd586ef22affe071c51b2cd5eb\"");
    await queryRunner.query("ALTER TABLE \"order\" DROP CONSTRAINT \"FK_530376662de2b4138653194be2b\"");
    await queryRunner.query("ALTER TABLE \"order\" DROP CONSTRAINT \"FK_8a583acc24e13bcf84b1b9d0d20\"");
    await queryRunner.query("ALTER TABLE \"order\" DROP CONSTRAINT \"FK_20981b2b68bf03393c44dd1b9d7\"");
    await queryRunner.query("ALTER TABLE \"review\" DROP CONSTRAINT \"FK_2bbe7b10857bd93ca651699037b\"");
    await queryRunner.query("ALTER TABLE \"review\" DROP CONSTRAINT \"FK_34413365b39e3bf5bea866569b4\"");
    await queryRunner.query("ALTER TABLE \"review\" DROP CONSTRAINT \"FK_630f200bca6cd83918a0a4479ff\"");
    await queryRunner.query("ALTER TABLE \"license\" DROP CONSTRAINT \"FK_05d20a9b7c596fe15467a4d1279\"");
    await queryRunner.query("ALTER TABLE \"license\" DROP CONSTRAINT \"FK_e368cd7219d66f7e97dd52ce91a\"");
    await queryRunner.query("ALTER TABLE \"license\" DROP CONSTRAINT \"FK_78fd970f6ec6ef41f8eae138e58\"");
    await queryRunner.query("ALTER TABLE \"favorite\" DROP CONSTRAINT \"FK_268e16a2e8408d2e70bf77b8ae2\"");
    await queryRunner.query("ALTER TABLE \"favorite\" DROP CONSTRAINT \"FK_c58c744f101a916108d5ee7a7a3\"");
    await queryRunner.query("DROP INDEX \"public\".\"IDX_0c1467bd2ae2fa944b3dcdf8b9\"");
    await queryRunner.query("DROP INDEX \"public\".\"IDX_e21fe37e3bf2e746857a838293\"");
    await queryRunner.query("DROP TABLE \"version_tags_tag\"");
    await queryRunner.query("DROP TABLE \"ticket\"");
    await queryRunner.query("DROP TYPE \"public\".\"ticket_status_enum\"");
    await queryRunner.query("DROP TABLE \"demo_upload\"");
    await queryRunner.query("DROP TABLE \"artwork\"");
    await queryRunner.query("DROP TYPE \"public\".\"artwork_visibility_enum\"");
    await queryRunner.query("DROP TABLE \"comment\"");
    await queryRunner.query("DROP TABLE \"like\"");
    await queryRunner.query("DROP TABLE \"user\"");
    await queryRunner.query("DROP TABLE \"view\"");
    await queryRunner.query("DROP TABLE \"notification\"");
    await queryRunner.query("DROP TYPE \"public\".\"notification_type_enum\"");
    await queryRunner.query("DROP TABLE \"intent\"");
    await queryRunner.query("DROP TABLE \"version\"");
    await queryRunner.query("DROP TYPE \"public\".\"version_use_enum\"");
    await queryRunner.query("DROP TYPE \"public\".\"version_license_enum\"");
    await queryRunner.query("DROP TYPE \"public\".\"version_type_enum\"");
    await queryRunner.query("DROP TYPE \"public\".\"version_availability_enum\"");
    await queryRunner.query("DROP TABLE \"tag\"");
    await queryRunner.query("DROP TABLE \"order\"");
    await queryRunner.query("DROP TYPE \"public\".\"order_status_enum\"");
    await queryRunner.query("DROP TYPE \"public\".\"order_type_enum\"");
    await queryRunner.query("DROP TABLE \"review\"");
    await queryRunner.query("DROP TABLE \"license\"");
    await queryRunner.query("DROP TYPE \"public\".\"license_usage_enum\"");
    await queryRunner.query("DROP TYPE \"public\".\"license_type_enum\"");
    await queryRunner.query("DROP TABLE \"discount\"");
    await queryRunner.query("DROP TABLE \"media\"");
    await queryRunner.query("DROP TYPE \"public\".\"media_orientation_enum\"");
    await queryRunner.query("DROP TABLE \"cover\"");
    await queryRunner.query("DROP TYPE \"public\".\"cover_orientation_enum\"");
    await queryRunner.query("DROP TABLE \"favorite\"");
    await queryRunner.query("DROP TABLE \"avatar\"");
    await queryRunner.query("DROP TYPE \"public\".\"avatar_orientation_enum\"");
  }
}
