export const upload = {
  artwork: {
    fileSize: 10 * 1024 * 1024,
    fileDimensions: { height: 1200, width: 1200 },
    fileTransform: { width: 500 },
    mimeTypes: ["image/jpg", "image/jpeg", "image/gif", "image/png"],
  },
  user: {
    fileSize: 5 * 1024 * 1024,
    fileDimensions: { height: 150, width: 150 },
    mimeTypes: ["image/jpg", "image/jpeg", "image/png"],
  },
};

export const payment = {
  appFee: 0.15,
  buyerFee: {
    multiplier: 0.05,
    addend: 2.35,
  },
};

export const countries = [
  { name: "Afghanistan", code: "AF", supported: false },
  { name: "Åland Islands", code: "AX", supported: false },
  { name: "Albania", code: "AL", supported: false },
  { name: "Algeria", code: "DZ", supported: false },
  { name: "American Samoa", code: "AS", supported: false },
  { name: "AndorrA", code: "AD", supported: false },
  { name: "Angola", code: "AO", supported: false },
  { name: "Anguilla", code: "AI", supported: false },
  { name: "Antarctica", code: "AQ", supported: false },
  { name: "Antigua and Barbuda", code: "AG", supported: false },
  { name: "Argentina", code: "AR", supported: false },
  { name: "Armenia", code: "AM", supported: false },
  { name: "Aruba", code: "AW", supported: false },
  { name: "Australia", code: "AU", supported: true },
  { name: "Austria", code: "AT", supported: true },
  { name: "Azerbaijan", code: "AZ", supported: false },
  { name: "Bahamas", code: "BS", supported: false },
  { name: "Bahrain", code: "BH", supported: false },
  { name: "Bangladesh", code: "BD", supported: false },
  { name: "Barbados", code: "BB", supported: false },
  { name: "Belarus", code: "BY", supported: false },
  { name: "Belgium", code: "BE", supported: true },
  { name: "Belize", code: "BZ", supported: false },
  { name: "Benin", code: "BJ", supported: false },
  { name: "Bermuda", code: "BM", supported: false },
  { name: "Bhutan", code: "BT", supported: false },
  { name: "Bolivia", code: "BO", supported: false },
  { name: "Bosnia and Herzegovina", code: "BA", supported: false },
  { name: "Botswana", code: "BW", supported: false },
  { name: "Bouvet Island", code: "BV", supported: false },
  { name: "Brazil", code: "BR", supported: false },
  { name: "British Indian Ocean Territory", code: "IO", supported: false },
  { name: "Brunei Darussalam", code: "BN", supported: false },
  { name: "Bulgaria", code: "BG", supported: false },
  { name: "Burkina Faso", code: "BF", supported: false },
  { name: "Burundi", code: "BI", supported: false },
  { name: "Cambodia", code: "KH", supported: false },
  { name: "Cameroon", code: "CM", supported: false },
  { name: "Canada", code: "CA", supported: true },
  { name: "Cape Verde", code: "CV", supported: false },
  { name: "Cayman Islands", code: "KY", supported: false },
  { name: "Central African Republic", code: "CF", supported: false },
  { name: "Chad", code: "TD", supported: false },
  { name: "Chile", code: "CL", supported: false },
  { name: "China", code: "CN", supported: false },
  { name: "Christmas Island", code: "CX", supported: false },
  { name: "Cocos (Keeling) Islands", code: "CC", supported: false },
  { name: "Colombia", code: "CO", supported: false },
  { name: "Comoros", code: "KM", supported: false },
  { name: "Congo", code: "CG", supported: false },
  {
    name: "Congo, The Democratic Republic of the",
    code: "CD",
    supported: false,
  },
  { name: "Cook Islands", code: "CK", supported: false },
  { name: "Costa Rica", code: "CR", supported: false },
  { name: "Cote D'Ivoire", code: "CI", supported: false },
  { name: "Croatia", code: "HR", supported: false },
  { name: "Cuba", code: "CU", supported: false },
  { name: "Cyprus", code: "CY", supported: false },
  { name: "Czech Republic", code: "CZ", supported: false },
  { name: "Denmark", code: "DK", supported: true },
  { name: "Djibouti", code: "DJ", supported: false },
  { name: "Dominica", code: "DM", supported: false },
  { name: "Dominican Republic", code: "DO", supported: false },
  { name: "Ecuador", code: "EC", supported: false },
  { name: "Egypt", code: "EG", supported: false },
  { name: "El Salvador", code: "SV", supported: false },
  { name: "Equatorial Guinea", code: "GQ", supported: false },
  { name: "Eritrea", code: "ER", supported: false },
  { name: "Estonia", code: "EE", supported: true },
  { name: "Ethiopia", code: "ET", supported: false },
  { name: "Falkland Islands (Malvinas)", code: "FK", supported: false },
  { name: "Faroe Islands", code: "FO", supported: false },
  { name: "Fiji", code: "FJ", supported: false },
  { name: "Finland", code: "FI", supported: true },
  { name: "France", code: "FR", supported: true },
  { name: "French Guiana", code: "GF", supported: false },
  { name: "French Polynesia", code: "PF", supported: false },
  { name: "French Southern Territories", code: "TF", supported: false },
  { name: "Gabon", code: "GA", supported: false },
  { name: "Gambia", code: "GM", supported: false },
  { name: "Georgia", code: "GE", supported: false },
  { name: "Germany", code: "DE", supported: true },
  { name: "Ghana", code: "GH", supported: false },
  { name: "Gibraltar", code: "GI", supported: false },
  { name: "Greece", code: "GR", supported: true },
  { name: "Greenland", code: "GL", supported: false },
  { name: "Grenada", code: "GD", supported: false },
  { name: "Guadeloupe", code: "GP", supported: false },
  { name: "Guam", code: "GU", supported: false },
  { name: "Guatemala", code: "GT", supported: false },
  { name: "Guernsey", code: "GG", supported: false },
  { name: "Guinea", code: "GN", supported: false },
  { name: "Guinea-Bissau", code: "GW", supported: false },
  { name: "Guyana", code: "GY", supported: false },
  { name: "Haiti", code: "HT", supported: false },
  { name: "Heard Island and Mcdonald Islands", code: "HM", supported: false },
  { name: "Holy See (Vatican City State)", code: "VA", supported: false },
  { name: "Honduras", code: "HN", supported: false },
  { name: "Hong Kong", code: "HK", supported: true },
  { name: "Hungary", code: "HU", supported: false },
  { name: "Iceland", code: "IS", supported: false },
  { name: "India", code: "IN", supported: false },
  { name: "Indonesia", code: "ID", supported: false },
  { name: "Iran, Islamic Republic Of", code: "IR", supported: false },
  { name: "Iraq", code: "IQ", supported: false },
  { name: "Ireland", code: "IE", supported: true },
  { name: "Isle of Man", code: "IM", supported: false },
  { name: "Israel", code: "IL", supported: false },
  { name: "Italy", code: "IT", supported: true },
  { name: "Jamaica", code: "JM", supported: false },
  { name: "Japan", code: "JP", supported: true },
  { name: "Jersey", code: "JE", supported: false },
  { name: "Jordan", code: "JO", supported: false },
  { name: "Kazakhstan", code: "KZ", supported: false },
  { name: "Kenya", code: "KE", supported: false },
  { name: "Kiribati", code: "KI", supported: false },
  {
    name: "Korea, Democratic People'S Republic of",
    code: "KP",
    supported: false,
  },
  { name: "Korea, Republic of", code: "KR", supported: false },
  { name: "Kuwait", code: "KW", supported: false },
  { name: "Kyrgyzstan", code: "KG", supported: false },
  { name: "Lao People'S Democratic Republic", code: "LA", supported: false },
  { name: "Latvia", code: "LV", supported: true },
  { name: "Lebanon", code: "LB", supported: false },
  { name: "Lesotho", code: "LS", supported: false },
  { name: "Liberia", code: "LR", supported: false },
  { name: "Libyan Arab Jamahiriya", code: "LY", supported: false },
  { name: "Liechtenstein", code: "LI", supported: false },
  { name: "Lithuania", code: "LT", supported: true },
  { name: "Luxembourg", code: "LU", supported: true },
  { name: "Macao", code: "MO", supported: false },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    code: "MK",
    supported: false,
  },
  { name: "Madagascar", code: "MG", supported: false },
  { name: "Malawi", code: "MW", supported: false },
  { name: "Malaysia", code: "MY", supported: false },
  { name: "Maldives", code: "MV", supported: false },
  { name: "Mali", code: "ML", supported: false },
  { name: "Malta", code: "MT", supported: false },
  { name: "Marshall Islands", code: "MH", supported: false },
  { name: "Martinique", code: "MQ", supported: false },
  { name: "Mauritania", code: "MR", supported: false },
  { name: "Mauritius", code: "MU", supported: false },
  { name: "Mayotte", code: "YT", supported: false },
  { name: "Mexico", code: "MX", supported: false },
  { name: "Micronesia, Federated States of", code: "FM", supported: false },
  { name: "Moldova, Republic of", code: "MD", supported: false },
  { name: "Monaco", code: "MC", supported: false },
  { name: "Mongolia", code: "MN", supported: false },
  { name: "Montserrat", code: "MS", supported: false },
  { name: "Morocco", code: "MA", supported: false },
  { name: "Mozambique", code: "MZ", supported: false },
  { name: "Myanmar", code: "MM", supported: false },
  { name: "Namibia", code: "NA", supported: false },
  { name: "Nauru", code: "NR", supported: false },
  { name: "Nepal", code: "NP", supported: false },
  { name: "Netherlands", code: "NL", supported: true },
  { name: "Netherlands Antilles", code: "AN", supported: false },
  { name: "New Caledonia", code: "NC", supported: false },
  { name: "New Zealand", code: "NZ", supported: true },
  { name: "Nicaragua", code: "NI", supported: false },
  { name: "Niger", code: "NE", supported: false },
  { name: "Nigeria", code: "NG", supported: false },
  { name: "Niue", code: "NU", supported: false },
  { name: "Norfolk Island", code: "NF", supported: false },
  { name: "Northern Mariana Islands", code: "MP", supported: false },
  { name: "Norway", code: "NO", supported: true },
  { name: "Oman", code: "OM", supported: false },
  { name: "Pakistan", code: "PK", supported: false },
  { name: "Palau", code: "PW", supported: false },
  { name: "Palestinian Territory, Occupied", code: "PS", supported: false },
  { name: "Panama", code: "PA", supported: false },
  { name: "Papua New Guinea", code: "PG", supported: false },
  { name: "Paraguay", code: "PY", supported: false },
  { name: "Peru", code: "PE", supported: false },
  { name: "Philippines", code: "PH", supported: false },
  { name: "Pitcairn", code: "PN", supported: false },
  { name: "Poland", code: "PL", supported: true },
  { name: "Portugal", code: "PT", supported: true },
  { name: "Puerto Rico", code: "PR", supported: false },
  { name: "Qatar", code: "QA", supported: false },
  { name: "Reunion", code: "RE", supported: false },
  { name: "Romania", code: "RO", supported: false },
  { name: "Russian Federation", code: "RU", supported: false },
  { name: "RWANDA", code: "RW", supported: false },
  { name: "Saint Helena", code: "SH", supported: false },
  { name: "Saint Kitts and Nevis", code: "KN", supported: false },
  { name: "Saint Lucia", code: "LC", supported: false },
  { name: "Saint Pierre and Miquelon", code: "PM", supported: false },
  { name: "Saint Vincent and the Grenadines", code: "VC", supported: false },
  { name: "Samoa", code: "WS", supported: false },
  { name: "San Marino", code: "SM", supported: false },
  { name: "Sao Tome and Principe", code: "ST", supported: false },
  { name: "Saudi Arabia", code: "SA", supported: false },
  { name: "Senegal", code: "SN", supported: false },
  { name: "Serbia and Montenegro", code: "CS", supported: false },
  { name: "Seychelles", code: "SC", supported: false },
  { name: "Sierra Leone", code: "SL", supported: false },
  { name: "Singapore", code: "SG", supported: true },
  { name: "Slovakia", code: "SK", supported: true },
  { name: "Slovenia", code: "SI", supported: true },
  { name: "Solomon Islands", code: "SB", supported: false },
  { name: "Somalia", code: "SO", supported: false },
  { name: "South Africa", code: "ZA", supported: false },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    supported: false,
  },
  { name: "Spain", code: "ES", supported: true },
  { name: "Sri Lanka", code: "LK", supported: false },
  { name: "Sudan", code: "SD", supported: false },
  { name: "Suriname", code: "SR", supported: false },
  { name: "Svalbard and Jan Mayen", code: "SJ", supported: false },
  { name: "Swaziland", code: "SZ", supported: false },
  { name: "Sweden", code: "SE", supported: true },
  { name: "Switzerland", code: "CH", supported: true },
  { name: "Syrian Arab Republic", code: "SY", supported: false },
  { name: "Taiwan, Province of China", code: "TW", supported: false },
  { name: "Tajikistan", code: "TJ", supported: false },
  { name: "Tanzania, United Republic of", code: "TZ", supported: false },
  { name: "Thailand", code: "TH", supported: false },
  { name: "Timor-Leste", code: "TL", supported: false },
  { name: "Togo", code: "TG", supported: false },
  { name: "Tokelau", code: "TK", supported: false },
  { name: "Tonga", code: "TO", supported: false },
  { name: "Trinidad and Tobago", code: "TT", supported: false },
  { name: "Tunisia", code: "TN", supported: false },
  { name: "Turkey", code: "TR", supported: false },
  { name: "Turkmenistan", code: "TM", supported: false },
  { name: "Turks and Caicos Islands", code: "TC", supported: false },
  { name: "Tuvalu", code: "TV", supported: false },
  { name: "Uganda", code: "UG", supported: false },
  { name: "Ukraine", code: "UA", supported: false },
  { name: "United Arab Emirates", code: "AE", supported: false },
  { name: "United Kingdom", code: "GB", supported: true },
  { name: "United States", code: "US", supported: true },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    supported: false,
  },
  { name: "Uruguay", code: "UY", supported: false },
  { name: "Uzbekistan", code: "UZ", supported: false },
  { name: "Vanuatu", code: "VU", supported: false },
  { name: "Venezuela", code: "VE", supported: false },
  { name: "Viet Nam", code: "VN", supported: false },
  { name: "Virgin Islands, British", code: "VG", supported: false },
  { name: "Virgin Islands, U.S.", code: "VI", supported: false },
  { name: "Wallis and Futuna", code: "WF", supported: false },
  { name: "Western Sahara", code: "EH", supported: false },
  { name: "Yemen", code: "YE", supported: false },
  { name: "Zambia", code: "ZM", supported: false },
  { name: "Zimbabwe", code: "ZW", supported: false },
];
