export const upload = {
  artwork: {
    fileSize: 10 * 1024 * 1024,
    fileDimensions: { height: 1200, width: 1200 },
    fileTransform: { width: 640 },
    mimeTypes: ['image/jpg', 'image/jpeg', 'image/gif', 'image/png'],
  },
  user: {
    fileSize: 5 * 1024 * 1024,
    fileDimensions: { height: 150, width: 150 },
    mimeTypes: ['image/jpg', 'image/jpeg', 'image/png'],
  },
};

export const payment = {
  appFee: 0.15,
  buyerFee: {
    multiplier: 0.05,
    addend: 2.35,
  },
};

export const countries = [
  { name: 'Afghanistan', value: 'AF', supported: false },
  { name: 'Åland Islands', value: 'AX', supported: false },
  { name: 'Albania', value: 'AL', supported: false },
  { name: 'Algeria', value: 'DZ', supported: false },
  { name: 'American Samoa', value: 'AS', supported: false },
  { name: 'AndorrA', value: 'AD', supported: false },
  { name: 'Angola', value: 'AO', supported: false },
  { name: 'Anguilla', value: 'AI', supported: false },
  { name: 'Antarctica', value: 'AQ', supported: false },
  { name: 'Antigua and Barbuda', value: 'AG', supported: false },
  { name: 'Argentina', value: 'AR', supported: false },
  { name: 'Armenia', value: 'AM', supported: false },
  { name: 'Aruba', value: 'AW', supported: false },
  { name: 'Australia', value: 'AU', supported: true },
  { name: 'Austria', value: 'AT', supported: true },
  { name: 'Azerbaijan', value: 'AZ', supported: false },
  { name: 'Bahamas', value: 'BS', supported: false },
  { name: 'Bahrain', value: 'BH', supported: false },
  { name: 'Bangladesh', value: 'BD', supported: false },
  { name: 'Barbados', value: 'BB', supported: false },
  { name: 'Belarus', value: 'BY', supported: false },
  { name: 'Belgium', value: 'BE', supported: true },
  { name: 'Belize', value: 'BZ', supported: false },
  { name: 'Benin', value: 'BJ', supported: false },
  { name: 'Bermuda', value: 'BM', supported: false },
  { name: 'Bhutan', value: 'BT', supported: false },
  { name: 'Bolivia', value: 'BO', supported: false },
  { name: 'Bosnia and Herzegovina', value: 'BA', supported: false },
  { name: 'Botswana', value: 'BW', supported: false },
  { name: 'Bouvet Island', value: 'BV', supported: false },
  { name: 'Brazil', value: 'BR', supported: false },
  { name: 'British Indian Ocean Territory', value: 'IO', supported: false },
  { name: 'Brunei Darussalam', value: 'BN', supported: false },
  { name: 'Bulgaria', value: 'BG', supported: false },
  { name: 'Burkina Faso', value: 'BF', supported: false },
  { name: 'Burundi', value: 'BI', supported: false },
  { name: 'Cambodia', value: 'KH', supported: false },
  { name: 'Cameroon', value: 'CM', supported: false },
  { name: 'Canada', value: 'CA', supported: true },
  { name: 'Cape Verde', value: 'CV', supported: false },
  { name: 'Cayman Islands', value: 'KY', supported: false },
  { name: 'Central African Republic', value: 'CF', supported: false },
  { name: 'Chad', value: 'TD', supported: false },
  { name: 'Chile', value: 'CL', supported: false },
  { name: 'China', value: 'CN', supported: false },
  { name: 'Christmas Island', value: 'CX', supported: false },
  { name: 'Cocos (Keeling) Islands', value: 'CC', supported: false },
  { name: 'Colombia', value: 'CO', supported: false },
  { name: 'Comoros', value: 'KM', supported: false },
  { name: 'Congo', value: 'CG', supported: false },
  {
    name: 'Congo, The Democratic Republic of the',
    value: 'CD',
    supported: false,
  },
  { name: 'Cook Islands', value: 'CK', supported: false },
  { name: 'Costa Rica', value: 'CR', supported: false },
  { name: "Cote D'Ivoire", value: 'CI', supported: false },
  { name: 'Croatia', value: 'HR', supported: false },
  { name: 'Cuba', value: 'CU', supported: false },
  { name: 'Cyprus', value: 'CY', supported: false },
  { name: 'Czech Republic', value: 'CZ', supported: false },
  { name: 'Denmark', value: 'DK', supported: true },
  { name: 'Djibouti', value: 'DJ', supported: false },
  { name: 'Dominica', value: 'DM', supported: false },
  { name: 'Dominican Republic', value: 'DO', supported: false },
  { name: 'Ecuador', value: 'EC', supported: false },
  { name: 'Egypt', value: 'EG', supported: false },
  { name: 'El Salvador', value: 'SV', supported: false },
  { name: 'Equatorial Guinea', value: 'GQ', supported: false },
  { name: 'Eritrea', value: 'ER', supported: false },
  { name: 'Estonia', value: 'EE', supported: true },
  { name: 'Ethiopia', value: 'ET', supported: false },
  { name: 'Falkland Islands (Malvinas)', value: 'FK', supported: false },
  { name: 'Faroe Islands', value: 'FO', supported: false },
  { name: 'Fiji', value: 'FJ', supported: false },
  { name: 'Finland', value: 'FI', supported: true },
  { name: 'France', value: 'FR', supported: true },
  { name: 'French Guiana', value: 'GF', supported: false },
  { name: 'French Polynesia', value: 'PF', supported: false },
  { name: 'French Southern Territories', value: 'TF', supported: false },
  { name: 'Gabon', value: 'GA', supported: false },
  { name: 'Gambia', value: 'GM', supported: false },
  { name: 'Georgia', value: 'GE', supported: false },
  { name: 'Germany', value: 'DE', supported: true },
  { name: 'Ghana', value: 'GH', supported: false },
  { name: 'Gibraltar', value: 'GI', supported: false },
  { name: 'Greece', value: 'GR', supported: true },
  { name: 'Greenland', value: 'GL', supported: false },
  { name: 'Grenada', value: 'GD', supported: false },
  { name: 'Guadeloupe', value: 'GP', supported: false },
  { name: 'Guam', value: 'GU', supported: false },
  { name: 'Guatemala', value: 'GT', supported: false },
  { name: 'Guernsey', value: 'GG', supported: false },
  { name: 'Guinea', value: 'GN', supported: false },
  { name: 'Guinea-Bissau', value: 'GW', supported: false },
  { name: 'Guyana', value: 'GY', supported: false },
  { name: 'Haiti', value: 'HT', supported: false },
  { name: 'Heard Island and Mcdonald Islands', value: 'HM', supported: false },
  { name: 'Holy See (Vatican City State)', value: 'VA', supported: false },
  { name: 'Honduras', value: 'HN', supported: false },
  { name: 'Hong Kong', value: 'HK', supported: true },
  { name: 'Hungary', value: 'HU', supported: false },
  { name: 'Iceland', value: 'IS', supported: false },
  { name: 'India', value: 'IN', supported: false },
  { name: 'Indonesia', value: 'ID', supported: false },
  { name: 'Iran, Islamic Republic Of', value: 'IR', supported: false },
  { name: 'Iraq', value: 'IQ', supported: false },
  { name: 'Ireland', value: 'IE', supported: true },
  { name: 'Isle of Man', value: 'IM', supported: false },
  { name: 'Israel', value: 'IL', supported: false },
  { name: 'Italy', value: 'IT', supported: true },
  { name: 'Jamaica', value: 'JM', supported: false },
  { name: 'Japan', value: 'JP', supported: true },
  { name: 'Jersey', value: 'JE', supported: false },
  { name: 'Jordan', value: 'JO', supported: false },
  { name: 'Kazakhstan', value: 'KZ', supported: false },
  { name: 'Kenya', value: 'KE', supported: false },
  { name: 'Kiribati', value: 'KI', supported: false },
  {
    name: "Korea, Democratic People'S Republic of",
    value: 'KP',
    supported: false,
  },
  { name: 'Korea, Republic of', value: 'KR', supported: false },
  { name: 'Kuwait', value: 'KW', supported: false },
  { name: 'Kyrgyzstan', value: 'KG', supported: false },
  { name: "Lao People'S Democratic Republic", value: 'LA', supported: false },
  { name: 'Latvia', value: 'LV', supported: true },
  { name: 'Lebanon', value: 'LB', supported: false },
  { name: 'Lesotho', value: 'LS', supported: false },
  { name: 'Liberia', value: 'LR', supported: false },
  { name: 'Libyan Arab Jamahiriya', value: 'LY', supported: false },
  { name: 'Liechtenstein', value: 'LI', supported: false },
  { name: 'Lithuania', value: 'LT', supported: true },
  { name: 'Luxembourg', value: 'LU', supported: true },
  { name: 'Macao', value: 'MO', supported: false },
  {
    name: 'Macedonia, The Former Yugoslav Republic of',
    value: 'MK',
    supported: false,
  },
  { name: 'Madagascar', value: 'MG', supported: false },
  { name: 'Malawi', value: 'MW', supported: false },
  { name: 'Malaysia', value: 'MY', supported: false },
  { name: 'Maldives', value: 'MV', supported: false },
  { name: 'Mali', value: 'ML', supported: false },
  { name: 'Malta', value: 'MT', supported: false },
  { name: 'Marshall Islands', value: 'MH', supported: false },
  { name: 'Martinique', value: 'MQ', supported: false },
  { name: 'Mauritania', value: 'MR', supported: false },
  { name: 'Mauritius', value: 'MU', supported: false },
  { name: 'Mayotte', value: 'YT', supported: false },
  { name: 'Mexico', value: 'MX', supported: false },
  { name: 'Micronesia, Federated States of', value: 'FM', supported: false },
  { name: 'Moldova, Republic of', value: 'MD', supported: false },
  { name: 'Monaco', value: 'MC', supported: false },
  { name: 'Mongolia', value: 'MN', supported: false },
  { name: 'Montserrat', value: 'MS', supported: false },
  { name: 'Morocco', value: 'MA', supported: false },
  { name: 'Mozambique', value: 'MZ', supported: false },
  { name: 'Myanmar', value: 'MM', supported: false },
  { name: 'Namibia', value: 'NA', supported: false },
  { name: 'Nauru', value: 'NR', supported: false },
  { name: 'Nepal', value: 'NP', supported: false },
  { name: 'Netherlands', value: 'NL', supported: true },
  { name: 'Netherlands Antilles', value: 'AN', supported: false },
  { name: 'New Caledonia', value: 'NC', supported: false },
  { name: 'New Zealand', value: 'NZ', supported: true },
  { name: 'Nicaragua', value: 'NI', supported: false },
  { name: 'Niger', value: 'NE', supported: false },
  { name: 'Nigeria', value: 'NG', supported: false },
  { name: 'Niue', value: 'NU', supported: false },
  { name: 'Norfolk Island', value: 'NF', supported: false },
  { name: 'Northern Mariana Islands', value: 'MP', supported: false },
  { name: 'Norway', value: 'NO', supported: true },
  { name: 'Oman', value: 'OM', supported: false },
  { name: 'Pakistan', value: 'PK', supported: false },
  { name: 'Palau', value: 'PW', supported: false },
  { name: 'Palestinian Territory, Occupied', value: 'PS', supported: false },
  { name: 'Panama', value: 'PA', supported: false },
  { name: 'Papua New Guinea', value: 'PG', supported: false },
  { name: 'Paraguay', value: 'PY', supported: false },
  { name: 'Peru', value: 'PE', supported: false },
  { name: 'Philippines', value: 'PH', supported: false },
  { name: 'Pitcairn', value: 'PN', supported: false },
  { name: 'Poland', value: 'PL', supported: true },
  { name: 'Portugal', value: 'PT', supported: true },
  { name: 'Puerto Rico', value: 'PR', supported: false },
  { name: 'Qatar', value: 'QA', supported: false },
  { name: 'Reunion', value: 'RE', supported: false },
  { name: 'Romania', value: 'RO', supported: false },
  { name: 'Russian Federation', value: 'RU', supported: false },
  { name: 'RWANDA', value: 'RW', supported: false },
  { name: 'Saint Helena', value: 'SH', supported: false },
  { name: 'Saint Kitts and Nevis', value: 'KN', supported: false },
  { name: 'Saint Lucia', value: 'LC', supported: false },
  { name: 'Saint Pierre and Miquelon', value: 'PM', supported: false },
  { name: 'Saint Vincent and the Grenadines', value: 'VC', supported: false },
  { name: 'Samoa', value: 'WS', supported: false },
  { name: 'San Marino', value: 'SM', supported: false },
  { name: 'Sao Tome and Principe', value: 'ST', supported: false },
  { name: 'Saudi Arabia', value: 'SA', supported: false },
  { name: 'Senegal', value: 'SN', supported: false },
  { name: 'Serbia and Montenegro', value: 'CS', supported: false },
  { name: 'Seychelles', value: 'SC', supported: false },
  { name: 'Sierra Leone', value: 'SL', supported: false },
  { name: 'Singapore', value: 'SG', supported: true },
  { name: 'Slovakia', value: 'SK', supported: true },
  { name: 'Slovenia', value: 'SI', supported: true },
  { name: 'Solomon Islands', value: 'SB', supported: false },
  { name: 'Somalia', value: 'SO', supported: false },
  { name: 'South Africa', value: 'ZA', supported: false },
  {
    name: 'South Georgia and the South Sandwich Islands',
    value: 'GS',
    supported: false,
  },
  { name: 'Spain', value: 'ES', supported: true },
  { name: 'Sri Lanka', value: 'LK', supported: false },
  { name: 'Sudan', value: 'SD', supported: false },
  { name: 'Suriname', value: 'SR', supported: false },
  { name: 'Svalbard and Jan Mayen', value: 'SJ', supported: false },
  { name: 'Swaziland', value: 'SZ', supported: false },
  { name: 'Sweden', value: 'SE', supported: true },
  { name: 'Switzerland', value: 'CH', supported: true },
  { name: 'Syrian Arab Republic', value: 'SY', supported: false },
  { name: 'Taiwan, Province of China', value: 'TW', supported: false },
  { name: 'Tajikistan', value: 'TJ', supported: false },
  { name: 'Tanzania, United Republic of', value: 'TZ', supported: false },
  { name: 'Thailand', value: 'TH', supported: false },
  { name: 'Timor-Leste', value: 'TL', supported: false },
  { name: 'Togo', value: 'TG', supported: false },
  { name: 'Tokelau', value: 'TK', supported: false },
  { name: 'Tonga', value: 'TO', supported: false },
  { name: 'Trinidad and Tobago', value: 'TT', supported: false },
  { name: 'Tunisia', value: 'TN', supported: false },
  { name: 'Turkey', value: 'TR', supported: false },
  { name: 'Turkmenistan', value: 'TM', supported: false },
  { name: 'Turks and Caicos Islands', value: 'TC', supported: false },
  { name: 'Tuvalu', value: 'TV', supported: false },
  { name: 'Uganda', value: 'UG', supported: false },
  { name: 'Ukraine', value: 'UA', supported: false },
  { name: 'United Arab Emirates', value: 'AE', supported: false },
  { name: 'United Kingdom', value: 'GB', supported: true },
  { name: 'United States', value: 'US', supported: true },
  {
    name: 'United States Minor Outlying Islands',
    value: 'UM',
    supported: false,
  },
  { name: 'Uruguay', value: 'UY', supported: false },
  { name: 'Uzbekistan', value: 'UZ', supported: false },
  { name: 'Vanuatu', value: 'VU', supported: false },
  { name: 'Venezuela', value: 'VE', supported: false },
  { name: 'Viet Nam', value: 'VN', supported: false },
  { name: 'Virgin Islands, British', value: 'VG', supported: false },
  { name: 'Virgin Islands, U.S.', value: 'VI', supported: false },
  { name: 'Wallis and Futuna', value: 'WF', supported: false },
  { name: 'Western Sahara', value: 'EH', supported: false },
  { name: 'Yemen', value: 'YE', supported: false },
  { name: 'Zambia', value: 'ZM', supported: false },
  { name: 'Zimbabwe', value: 'ZW', supported: false },
];
