name: Fly Deploy - staging
on:
  push:
    branches:
      - 'master'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
jobs:
  deploy:
      name: Deploy staging
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: yarn run deploy:staging