name: Validate deployment

on:
  push:
    branches:
      - master
  pull_request:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
jobs:
  validate-server:
    name: Validate Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Tests
        run: |
          yarn run proxy:test & yarn run test

  validate-client:
    name: Validate Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build